// <auto-generated />
using System;
using BankSys.Persistence;
using BankSys.Persistence.CustomerManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankSys.Persistence.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20220228213900_VersionAdded")]
    partial class VersionAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("BankSys.Persistence.Scheme.BankAccountDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerDbId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerDbId");

                    b.ToTable("BankAccountDb");
                });

            modelBuilder.Entity("BankSys.Persistence.Scheme.CustomerDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("emailAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BankSys.Persistence.Scheme.BankAccountDb", b =>
                {
                    b.HasOne("BankSys.Persistence.Scheme.CustomerDb", null)
                        .WithMany("BankAccounts")
                        .HasForeignKey("CustomerDbId");
                });

            modelBuilder.Entity("BankSys.Persistence.Scheme.CustomerDb", b =>
                {
                    b.Navigation("BankAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
